set -as terminal-features 'xterm-256color:sixel'
# set -g default-terminal "tmux-256color"
set -as terminal-features 'tmux-256color:sixel'

unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind a last-window

unbind %
bind s split-window -v

unbind '"'
bind v split-window -h

bind -r m resize-pane -Z

set -g mouse on

set -g base-index 1
set -g renumber-windows on
set -g automatic-rename on

set -g focus-events on

setw -g aggressive-resize on

bind R source '/home/ali/.tmux.conf' \; display-message "tmux config reloaded!"
set-window-option -g automatic-rename

setw -g mode-keys vi

set-option -g status-style bg=default
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind-key -n DoubleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-word \; send-keys -X copy-pipe-no-clear "xclip -selection clipboard -in" \; run "sleep 0.15" \; send-keys -X cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"


# set -g detach-on-destroy off  # don't exit from tmux when closing a session

# is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

# Resize panes using Alt + H/J/K/L
bind-key -n M-h resize-pane -L 4
bind-key -n M-j resize-pane -D 4
bind-key -n M-k resize-pane -U 4
bind-key -n M-l resize-pane -R 4

bind-key = select-layout -E

# bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
# bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
# bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
# bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }

# bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
# bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
# bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
# bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'

# Install with <prefix>I
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'sainnhe/tmux-fzf'
# TMUX_FZF_LAUNCH_KEY="C-f"
# TMUX_FZF_PREVIEW=1

# style points
set -g status-left "#[fg=#8aadf4]󰰡#[fg=#f7768e] #S#[bg=#1a1b2c]"
set -g window-status-format "#[bg=#1a1b2c]#[fg=#8087a2]#I #W  #[fg=#8087a2]"
set -g window-status-current-format "#[fg=#e0af68]#I #W  #[fg=#e0af68]"
set -g status-justify centre
set -g status-right '#[fg=#ff9e64] #[fg=#ff9e64] %Y-%m-%d '


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

run '~/.tmux/plugins/tpm/tpm'
